services:
  grass-node:
    build:
      context: .
      dockerfile: grass-node.dockerfile
    environment:
      USER_EMAIL: ${USER_EMAIL}
      USER_PASSWORD: ${USER_PASSWORD}
      EXTENSION_IDS: ${EXTENSION_IDS}
      EXTENSION_URLS: ${EXTENSION_URLS}
      CRX_DOWNLOAD_URLS: ${CRX_DOWNLOAD_URLS}
      MAX_RETRY_MULTIPLIER: ${MAX_RETRY_MULTIPLIER}
    ports:
      - "8080:8080"
    tty: true
    stdin_open: true
    develop:
      watch:
        - action: sync
          path: ./
          target: /app/

