services:
  grass-desktop:
    build:
      context: .
      dockerfile: grass-desktop.dockerfile
    environment:
      USER_EMAIL: ${USER_EMAIL}
      USER_PASSWORD: ${USER_PASSWORD}
      MAX_RETRY_MULTIPLIER: ${MAX_RETRY_MULTIPLIER:-3}
      TRY_AUTOLOGIN: ${TRY_AUTOLOGIN:-true}
      CUSTOMIZE: ${CUSTOMIZE:-true}
      AUTO_START_BROWSER: ${AUTO_START_BROWSER:-false}
      AUTO_START_XTERM: ${AUTO_START_XTERM:-false}
      
    ports:
      - "5900:5900"
      - "6080:6080"
    tty: true
    stdin_open: true
    # develop:
    #   watch:
    #     - action: sync
    #       path: ./
    #       target: /app/

