version: "3.9"
services:
  grass:
    build:
      context: .
      dockerfile: grass.dockerfile
    container_name: grass
    hostname: my_device
    image: mrcolorrain/grass
    environment:
      - USER_EMAIL=${USER_EMAIL}
      - USER_PASSWORD=${USER_PASSWORD}
      - TRY_AUTOLOGIN=${TRY_AUTOLOGIN:-true}
      - MAX_RETRY_MULTIPLIER=${MAX_RETRY_MULTIPLIER:-3}
      - HEADLESS=${HEADLESS:-true}
    restart: unless-stopped
