name: Grass Dev Build and Push

on:
  push:
    tags:
      - 'BDL_grass-dev*'

permissions:
  contents: write

env:
  GRASS_IMAGE_NAME: 'mrcolorrain/grass'
  GRASS_VERSION_FILE_PATH: '.githubworkflows.grass_current_version'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Read Grass Version
        id: read-version
        run: |
          if [ -f "${{ env.GRASS_VERSION_FILE_PATH }}" ]; then
            VERSION=$(cat "${{ env.GRASS_VERSION_FILE_PATH }}")
            echo "version=$VERSION" >> $GITHUB_OUTPUT
          else
            echo "Version file not found. Exiting."
            exit 1
          fi

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Grass Dev Image
        uses: docker/build-push-action@v6
        with:
          file: "grass.dockerfile"
          push: true
          tags: |
            ${{ env.GRASS_IMAGE_NAME }}:${{ steps.read-version.outputs.version }}-dev
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          cache-from: type=gha
          cache-to: type=gha,mode=max
