name: Grass-Node Dev Build and Push

on:
  push:
    tags:
      - 'BLD_grass-node_*'

permissions:
  contents: write

env:
  GRASS_NODE_IMAGE_NAME: 'mrcolorrain/grass-node'

jobs:
  dev-build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract Grass-Node Version
        id: extract-version
        run: |
          # Extract version by stripping the 'BLD_grass-node_' prefix
          VERSION="${GITHUB_REF#refs/tags/BLD_grass-node_}"
          echo "version=$VERSION" >> $GITHUB_ENV
          echo "Extracted Grass-Node version: $VERSION"

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Grass-Node Dev Image
        uses: docker/build-push-action@v6
        with:
          file: "grass-node.dockerfile"
          push: true
          tags: |
            ${{ env.GRASS_NODE_IMAGE_NAME }}:${{ env.version }}
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          cache-from: type=gha
          cache-to: type=gha,mode=max
